# FROM maven:3.8-openjdk-8 AS build
# COPY . .
# RUN mvn clean package -DskipTests

# FROM openjdk:8-jdk-slim
# COPY --from=build /target/freelancing-0.0.1-SNAPSHOT.jar freelancing.jar

# EXPOSE 8080
# ENTRYPOINT ["java","-jar","freelancing.jar"]
