FROM maven:3.8-openjdk-8 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:8-jdk-slim
COPY --from=build /target/portfolio-builder-0.0.1-SNAPSHOT.jar portfolio-builder.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","portfolio-builder.jar"]